"""
Django settings for commerce_app project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# env_path =  BASE_DIR / ".env"
# config = config(repository=RepositoryEnv(env_path))



# settings.py
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY")

GEMINI_API_KEY = config("GEMINI_API_KEY")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure--d((3m#c=k_5s3^z_j%i%&*#e(!4j5#p993*921^)p6*^#ozai')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'c_app',
    'social_django',
    
    ]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

LOGIN_URL = 'http://127.0.0.1:8000/login/'
LOGOUT_URL = 'http://127.0.0.1:8000/logout/'
LOGIN_REDIRECT_URL = 'http://127.0.0.1:8000/home/'
LOGOUT_REDIRECT_URL = 'http://127.0.0.1:8000/login/'

SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS={
    'prompt':'select_account'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTH_USER_MODEL = 'c_app.User'
ROOT_URLCONF = 'commerce_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'commerce_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# JAZZMIN CONFIGURATION
JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "My Admin",
    "site_header": "My Project",
    "site_brand": "My Project",
    "site_logo": "app/logo.png",   # put logo in app/static/app/logo.png
    "welcome_sign": "Welcome back, Vamsi!",
    "copyright": "",
    "show_ui_builder": True,       # enables live UI customizer (paintbrush icon)


    # Top Menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "auth"},   # dropdown for auth app
        {"model": "auth.User"},  # direct link to User model
        {"name": "Docs", "url": "https://docs.djangoproject.com/", "new_window": True},
    ],

    # User Menu
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    ],

    # Icons (Font Awesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Add your models here, e.g. "yourapp.YourModel": "fas fa-database",
    },

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth"],   # puts auth app first
    "hide_apps": [],                     # e.g. ["admin"]
    "hide_models": [],                   # e.g. ["auth.group"]

    "custom_links": {
        "auth": [{
            "name": "Quick Stats",
            "url": "admin:index",
            "icon": "fas fa-chart-line",
            "permissions": ["auth.view_user"],
        }]
    },

    # Change form layout
    "changeform_format": "horizontal_tabs",   # options: single, horizontal_tabs, vertical_tabs, collapsible, carousel
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },

    # Custom static files (optional)
    "custom_css": "common/css/main.css",
    "custom_js": "common/js/main.js",
}

# UI Theme Tweaks
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",         # light theme
    # "dark_mode_theme": "darkly",   # dark mode for users with dark mode devices
}





# JAZZMIN_SETTINGS = {
#     "site_title": "My Admin",
#     "site_header": "My Project",
#     "site_brand": "My Project",
#     # place a logo in your static files, e.g. app/static/app/logo.png
#     "site_logo": "app/logo.png",
#     "welcome_sign": "Welcome back, Vamsi!",
#     "copyright": "",
#     "show_ui_builder": True,   # enables live UI Customizer (top-right paintbrush)
# }

# JAZZMIN_UI_TWEAKS = {
#     "theme": "flatly",
#     "dark_mode_theme": "darkly",
# }


# JAZZMIN_SETTINGS |= {
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.User": "fas fa-user",
#         "auth.Group": "fas fa-users",
#         "c_app.Product": "fas fa-database",
#     },
# }


# JAZZMIN_SETTINGS["topmenu_links"] = [
#     {"name": "Dashboard", "url": "admin:index"},
#     {"app": "auth"},                 # dropdown of all auth models
#     {"model": "auth.User"},          # direct to Users changelist
#     {"name": "Docs", "url": "https://docs.djangoproject.com/", "new_window": True},
# ]

# JAZZMIN_SETTINGS["usermenu_links"] = [
#     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
# ]


# JAZZMIN_SETTINGS |= {
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "order_with_respect_to": ["auth"],    # put auth first
#     "hide_apps": [],                      # e.g. ["admin"]
#     "hide_models": [],                    # e.g. ["auth.group"]
#     "custom_links": {
#         "auth": [{
#             "name": "Quick Stats",
#             "url": "admin:index",
#             "icon": "fas fa-chart-line",
#             "permissions": ["auth.view_user"],
#         }]
#     },
# }


# JAZZMIN_SETTINGS |= {
#     "changeform_format": "horizontal_tabs",  # options: single, horizontal_tabs, vertical_tabs, collapsible, carousel
#     "changeform_format_overrides": {"auth.user": "collapsible"},
# }
# JAZZMIN_SETTINGS |= {
#     "custom_css": "common/css/main.css",
#     "custom_js": "common/js/main.js",
# }
