# Generated by Django 5.2.3 on 2025-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0003_remove_cartitem_cart_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cart'), (1, 'Pending'), (2, 'Confirmed'), (3, 'Shipped'), (4, 'Delivered'), (5, 'Cancelled')], default=0, null=True),
        ),
    ]
